### ISSUE TITLE
Enable for Python 3.10

### ISSUE THREAD

**Issue by disrupted** [cdce8p/python-typing-update#97]
Currently it doesn't run under Python 3.10. I am receiving the following error:

> ERROR: Package 'python-typing-update' requires a different Python: 3.10.0 not in '<3.10,>=3.8'

The requirement could be bumped https://github.com/cdce8p/python-typing-update/blob/267f67e46eaad1ee8853555ac50a2cda61d74876/setup.cfg#L22, not sure if there's anything else blocking this

**Comment by cdce8p** [comment]
Thanks for the reminder!
I bumped the Python version in #98 just to see if it could work. However, that showed why I added the limitation in the first place. `autoflake` might not support parsing of Python 3.10 code. I have to do some more work before finishing the PR.

For details: https://github.com/cdce8p/python-typing-update/pull/98#issuecomment-947162691

**Comment by cdce8p** [comment]
@disrupted Unfortunately, it's not really possible to use an alternative for `autoflake` at this time.
However, I did just remove the upper version constraint. That way you can at least use Python 3.10 to update older Python syntax.

**Comment by disrupted** [comment]
@cdce8p thanks for the update

**Comment by cdce8p** [comment]
Found another way -> #165. With a custom `autoflake` version, it's now also possible to parse `3.10` syntax 🎉

**Comment by disrupted** [comment]
@cdce8p that's great! thanks for the workaround
